repos:
  # Ruff - Fast Python linter and formatter (replaces black, isort, flake8)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # Pyright - Type checker for Python
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.361
    hooks:
      - id: pyright
        additional_dependencies: ['pydantic>=2.0.0', 'sqlalchemy>=2.0.0', 'fastapi>=0.100.0']

  # Gitleaks - Detect and prevent secrets in git repos
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks

  # Commitizen - Conventional commit messages
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.25.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # Additional security and quality checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: detect-private-key
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending

  # Bandit - Security linter
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-r, --skip=B101]
        files: ^(?!tests/).*\.py$