services:
  web:
    image: ghcr.io/mirqtio/leadfactory_v1:latest
    container_name: leadfactory_web
    restart: always
    ports:
      - "8000:8000"
    mem_limit: 512m
    memswap_limit: 512m
    environment:
      - DATABASE_URL=postgresql://leadfactory:${DB_PASSWORD:-leadfactory}@db:5432/leadfactory
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-}
      - HUMANLOOP_API_KEY=${HUMANLOOP_API_KEY:-}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY:-}
      - GOOGLE_PAGESPEED_API_KEY=${GOOGLE_PAGESPEED_API_KEY:-}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY:-}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-}
      - STRIPE_PRICE_ID=${STRIPE_PRICE_ID:-}
      - USE_STUBS=false
      - ENVIRONMENT=production
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15-alpine
    container_name: leadfactory_db
    restart: always
    mem_limit: 512m
    memswap_limit: 512m
    environment:
      - POSTGRES_USER=leadfactory
      - POSTGRES_PASSWORD=${DB_PASSWORD:-leadfactory}
      - POSTGRES_DB=leadfactory
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leadfactory"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: leadfactory_redis
    restart: always
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: