services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leadfactory_test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
      target: test
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/leadfactory_test
      USE_STUBS: "true"
      PYTHONPATH: /app
      ENVIRONMENT: test
      SECRET_KEY: test-secret-key-for-ci
      CI: "true"
    volumes:
      - ./coverage:/app/coverage
    command: pytest -m "not slow and not phase_future" --tb=short --cov=. --cov-report=html:coverage/html --cov-report=term --cov-report=xml:coverage.xml --cov-config=.coveragerc