# Ruff configuration for LeadFactory

# Python version target
target-version = "py311"

# Line length (matching black default)
line-length = 120

# Enable specific rule sets
select = [
    "E",     # pycodestyle errors
    "W",     # pycodestyle warnings  
    "F",     # pyflakes
]

# Ignore specific rules
ignore = [
    "E203",  # Whitespace before ':' (conflicts with black)
    "E501",  # Line too long (handled by formatter)
    "W503",  # Line break before binary operator
]

# Exclude paths
exclude = [
    ".git",
    ".ruff_cache",
    "__pycache__",
    "build",
    "dist",
    "venv",
    ".venv",
    "*.egg-info",
    ".pytest_cache",
    ".mypy_cache",
    "node_modules",
]

[per-file-ignores]
# Ignore import violations in specific files
"__init__.py" = ["F401"]