global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'leadfactory-monitor'

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape the LeadFactory application
  - job_name: 'leadfactory-app'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Scrape the stub server
  - job_name: 'leadfactory-stub'
    static_configs:
      - targets: ['stub-server:5010']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Scrape Redis exporter (if added later)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Scrape PostgreSQL exporter (if added later)
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

# Alerting configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - 'alertmanager:9093'

# Load rules once and periodically evaluate them
rule_files:
  # - "alerts/*.yml"
  # - "rules/*.yml"