# Production Configuration
environment: production
debug: false
log_level: INFO

# Database
database:
  url: ${DATABASE_URL}
  pool_size: 20
  max_overflow: 40
  pool_timeout: 30
  echo: false

# Redis
redis:
  url: ${REDIS_URL}
  max_connections: 50
  decode_responses: true

# Security
security:
  secret_key: ${SECRET_KEY}
  cors:
    allowed_origins:
      - https://yourdomain.com
      - https://www.yourdomain.com
    allow_credentials: true
    max_age: 3600
  
  # Rate limiting
  rate_limit:
    enabled: true
    default: "100/hour"
    burst: "10/minute"

# Performance
performance:
  workers: 4
  worker_class: uvicorn.workers.UvicornWorker
  worker_connections: 1000
  keepalive: 5
  timeout: 30

# Monitoring
monitoring:
  enabled: true
  prometheus:
    enabled: true
    port: 9090
  sentry:
    enabled: true
    dsn: ${SENTRY_DSN}
    traces_sample_rate: 0.1
  
# Health checks
health_checks:
  enabled: true
  database: true
  redis: true
  external_apis: true

# Email
email:
  provider: sendgrid
  from_email: ${SENDGRID_FROM_EMAIL}
  from_name: "LeadFactory"
  
# Stripe
stripe:
  mode: live
  success_url: https://yourdomain.com/purchase/success?session_id={CHECKOUT_SESSION_ID}
  cancel_url: https://yourdomain.com/purchase/cancel

# Feature flags
features:
  webhooks: true
  analytics: true
  experiments: true
  
# Logging
logging:
  format: json
  level: INFO
  file:
    enabled: true
    path: /var/log/leadfactory/app.log
    max_size: 100MB
    backup_count: 5
