#!/bin/bash
# Monitor LeadFactory deployment status

echo "🚀 LeadFactory Deployment Monitor"
echo "================================"
echo ""
echo "GitHub Actions URL:"
echo "https://github.com/mirqtio/LeadFactory_v1/actions/workflows/deploy.yml"
echo ""
echo "To check deployment status on your VPS:"
echo ""
echo "1. SSH into your VPS:"
echo "   ssh -p \$SSH_PORT \$SSH_USER@\$SSH_HOST"
echo ""
echo "2. Check if containers are running:"
echo "   cd /srv/leadfactory"
echo "   docker compose -f docker-compose.prod.yml ps"
echo ""
echo "3. Check container logs:"
echo "   docker compose -f docker-compose.prod.yml logs -f web"
echo ""
echo "4. Test health endpoint:"
echo "   curl http://localhost:8000/health"
echo ""
echo "5. Check database connection:"
echo "   docker compose -f docker-compose.prod.yml exec db psql -U leadfactory -c 'SELECT 1;'"
echo ""
echo "Common issues:"
echo "- If /srv/leadfactory doesn't exist, the deployment will create it"
echo "- If git clone fails, ensure VPS has SSH key added to GitHub"
echo "- If docker compose fails, check Docker is installed and user has permissions"
echo "- If health check fails, check logs for missing environment variables"