name: Build and Push Acceptance Container

on:
  push:
    branches: [main]
    paths:
      - 'containers/acceptance/**'
      - 'deployment/**'
      - 'profiles/**'
      - '.github/workflows/build-acceptance-container.yml'
  pull_request:
    branches: [main]
    paths:
      - 'containers/acceptance/**'
      - 'deployment/**'
      - 'profiles/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mirqtio/leadfactory_v1/acceptance-runner

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./containers/acceptance/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run security scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        continue-on-error: true
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Test container
        run: |
          # Pull the built image
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          
          # Test basic container functionality with a simple import test
          docker run --rm \
            -e REDIS_URL="redis://localhost:6379" \
            -e PRP_ID="test-container" \
            -e VPS_SSH_HOST="test.example.com" \
            -e VPS_SSH_USER="test" \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            bash -c 'python -c "import sys; print(\"✅ Container validation: Python interpreter working\"); import containers.acceptance.acceptance_runner; print(\"✅ Container validation: AcceptanceRunner module importable\")"'

  notify-deployment:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Notify successful container build
        run: |
          echo "🐳 Acceptance container built and pushed successfully"
          echo "Registry: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
          echo "Available for PRP-1060 acceptance testing workflows"