name: Linting and Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11.0"
    
    - name: Validate docker-compose files
      run: |
        docker compose -f docker-compose.yml config > /dev/null
        docker compose -f docker-compose.prod.yml config > /dev/null
    
    - name: Cache dependencies
      uses: actions/cache@v5
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 mypy bandit
    
    - name: Check pip dependencies
      run: |
        pip install -r requirements.txt
        pip check
    
    - name: Run Black
      run: black --check --diff .
      continue-on-error: true
    
    - name: Run isort
      run: isort --check-only --diff .
      continue-on-error: true
    
    - name: Run Flake8
      run: |
        # Check for critical errors that should fail CI
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Check for other style issues but don't fail CI
        flake8 . --count --exit-zero --max-complexity=15 --max-line-length=100 --ignore=F401,E402,W291,W293,F541,F811,F841,E712,E722,W391 --statistics
    
    - name: Run mypy type checking
      run: |
        mypy --install-types --non-interactive || true
        mypy . --ignore-missing-imports --show-error-codes --pretty || true
      continue-on-error: true
    
    - name: Run Bandit security scan
      run: bandit -r . -f json -o bandit-report.json || true
      
    - name: Upload Bandit report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: bandit-security-report
        path: bandit-report.json