name: Ultra-Minimal Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.11.0"
  DATABASE_URL: "sqlite:///tmp/test.db"
  USE_STUBS: "true"
  ENVIRONMENT: "test"
  SECRET_KEY: "test-secret-key-for-ci"

jobs:
  test-ultra-minimal:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Create tmp directory
      run: mkdir -p tmp
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install minimal dependencies
      run: |
        python -m pip install --upgrade pip
        # Install core dependencies from requirements.txt
        pip install -r requirements.txt
        # Install test dependencies
        pip install pytest pytest-timeout
    
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV
    
    - name: Run ultra-minimal tests
      run: |
        # Run only tests that don't require any external services or stub server
        python -m pytest -xvs tests/test_minimal_no_stubs.py --timeout=30
    
    - name: Summary
      if: always()
      run: |
        echo "Ultra-minimal test suite completed"
        echo "This workflow tests only core functionality without external dependencies"